version: '3.8'

services:
  php:
    build:
      context: ./docker/php
    volumes:
    - .:/var/www/html
    working_dir: /var/www/html
    networks:
    - score-app-network

  nginx:
    image: nginx:latest
    ports:
    - "8000:80"
    volumes:
    - .:/var/www/html
    - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    - ./var/log/nginx:/var/log/nginx
    depends_on:
    - php
    networks:
    - score-app-network

  mysql:
    image: mysql:latest
    volumes:
    - mysql-data:/var/lib/mysql
    networks:
    - score-app-network
    ports:
    - "33060:3306"
    environment:
      MYSQL_ROOT_PASSWORD: $MYSQL_ROOT_PASSWORD
      MYSQL_DATABASE: $MYSQL_DATABASE
      MYSQL_USER: $MYSQL_USER
      MYSQL_PASSWORD: $MYSQL_PASSWORD

###> doctrine/doctrine-bundle ###
  database:
    image: postgres:${POSTGRES_VERSION:-16}-alpine
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-app}
      # You should definitely change the password in production
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-!ChangeMe!}
      POSTGRES_USER: ${POSTGRES_USER:-app}
    volumes:
      - database_data:/var/lib/postgresql/data:rw
      # You may use a bind-mounted host directory instead, so that it is harder to accidentally remove the volume and lose all your data!
      # - ./docker/db/data:/var/lib/postgresql/data:rw
###< doctrine/doctrine-bundle ###

volumes:

###> doctrine/doctrine-bundle ###
  database_data:
###< doctrine/doctrine-bundle ###
  mysql-data:

networks:
  score-app-network:
    driver: bridge